name: fbr_dwc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.22.0
  box2d_flame: ^0.4.5
  path: ^1.6.4
  sqflite: ^1.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/football.png
    - assets/images/CartoonClouds.jpg
    - assets/images/wood.png
    - assets/images/pointer.png
    - assets/images/shadow.png
    - assets/images/grey.png
    - assets/images/worldcup.png
    - assets/images/goalscore.png
    - assets/images/score_to_start.png
    - assets/images/choose_country.png
    - assets/images/down_arrow.png
    - assets/images/pause_button.png
    - assets/images/play_button.png
    - assets/images/celeb_hand1.png
    - assets/images/celeb_hand2.png
    - assets/images/no1_fan.png
    - assets/images/fire.png
    - assets/images/0.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/row-1.png
    - assets/images/row-2.png
    - assets/images/row-3.png
    - assets/images/row-4.png
    - assets/images/row-5.png
    - assets/images/row-6.png
    - assets/images/row-7.png
    - assets/images/row-8.png
    - assets/images/row-9.png
    - assets/images/row-10.png
    - assets/images/row-11.png
    - assets/images/row-12.png
    - assets/images/row-13.png
    - assets/images/row-14.png
    - assets/images/row-15.png
    - assets/images/row-16.png
    - assets/images/row-17.png
    - assets/images/row-18.png
    - assets/images/row-19.png
    - assets/images/row-20.png
    - assets/images/row-21.png
    - assets/images/yem.png
    - assets/images/zam.png
    - assets/images/zim.png
    - assets/images/wal.png
    - assets/images/vie.png
    - assets/images/ven.png
    - assets/images/van.png
    - assets/images/uru.png
    - assets/images/vir.png
    - assets/images/usa.png
    - assets/images/uzb.png
    - assets/images/uae.png
    - assets/images/ukr.png
    - assets/images/uga.png
    - assets/images/tca.png
    - assets/images/tri.png
    - assets/images/tun.png
    - assets/images/tur.png
    - assets/images/tkm.png
    - assets/images/tga.png
    - assets/images/tog.png
    - assets/images/tls.png
    - assets/images/tha.png
    - assets/images/syr.png
    - assets/images/tah.png
    - assets/images/tjk.png
    - assets/images/tan.png
    - assets/images/sui.png
    - assets/images/swe.png
    - assets/images/sur.png
    - assets/images/sdn.png
    - assets/images/sri.png
    - assets/images/skn.png
    - assets/images/lca.png
    - assets/images/vin.png
    - assets/images/esp.png
    - assets/images/ssd.png
    - assets/images/rsa.png
    - assets/images/som.png
    - assets/images/sin.png
    - assets/images/svk.png
    - assets/images/svn.png
    - assets/images/sol.png
    - assets/images/sle.png
    - assets/images/sey.png
    - assets/images/srb.png
    - assets/images/sen.png
    - assets/images/smr.png
    - assets/images/stp.png
    - assets/images/ksa.png
    - assets/images/sco.png
    - assets/images/sam.png
    - assets/images/rwa.png
    - assets/images/rus.png
    - assets/images/rou.png
    - assets/images/por.png
    - assets/images/pur.png
    - assets/images/qat.png
    - assets/images/irl.png
    - assets/images/pol.png
    - assets/images/phi.png
    - assets/images/per.png
    - assets/images/par.png
    - assets/images/pak.png
    - assets/images/ple.png
    - assets/images/pan.png
    - assets/images/png.png
    - assets/images/oma.png
    - assets/images/nor.png
    - assets/images/nir.png
    - assets/images/mkd.png
    - assets/images/nzl.png
    - assets/images/nca.png
    - assets/images/nig.png
    - assets/images/nga.png
    - assets/images/ncl.png
    - assets/images/ned.png
    - assets/images/nep.png
    - assets/images/nam.png
    - assets/images/msr.png
    - assets/images/mar.png
    - assets/images/moz.png
    - assets/images/mya.png
    - assets/images/mne.png
    - assets/images/mng.png
    - assets/images/mda.png
    - assets/images/mex.png
    - assets/images/mli.png
    - assets/images/mlt.png
    - assets/images/mtn.png
    - assets/images/mri.png
    - assets/images/mdv.png
    - assets/images/mas.png
    - assets/images/mwi.png
    - assets/images/mad.png
    - assets/images/lie.png
    - assets/images/ltu.png
    - assets/images/lux.png
    - assets/images/mac.png
    - assets/images/lby.png
    - assets/images/lbr.png
    - assets/images/les.png
    - assets/images/lbn.png
    - assets/images/kuw.png
    - assets/images/kgz.png
    - assets/images/lao.png
    - assets/images/lva.png
    - assets/images/kvx.png
    - assets/images/kor.png
    - assets/images/prk.png
    - assets/images/ken.png
    - assets/images/jam.png
    - assets/images/jpn.png
    - assets/images/jor.png
    - assets/images/kaz.png
    - assets/images/ita.png
    - assets/images/isr.png
    - assets/images/irq.png
    - assets/images/irn.png
    - assets/images/hun.png
    - assets/images/isl.png
    - assets/images/ind.png
    - assets/images/idn.png
    - assets/images/hkg.png
    - assets/images/hon.png
    - assets/images/hai.png
    - assets/images/guy.png
    - assets/images/gum.png
    - assets/images/gua.png
    - assets/images/gui.png
    - assets/images/gnb.png
    - assets/images/grn.png
    - assets/images/gre.png
    - assets/images/gib.png
    - assets/images/gha.png
    - assets/images/gab.png
    - assets/images/gam.png
    - assets/images/geo.png
    - assets/images/ger.png
    - assets/images/fra.png
    - assets/images/fin.png
    - assets/images/fij.png
    - assets/images/fro.png
    - assets/images/eth.png
    - assets/images/swz.png
    - assets/images/est.png
    - assets/images/eri.png
    - assets/images/eqg.png
    - assets/images/eng.png
    - assets/images/slv.png
    - assets/images/egy.png
    - assets/images/ecu.png
    - assets/images/dom.png
    - assets/images/dma.png
    - assets/images/dji.png
    - assets/images/den.png
    - assets/images/cze.png
    - assets/images/cyp.png
    - assets/images/cuw.png
    - assets/images/cub.png
    - assets/images/cro.png
    - assets/images/civ.png
    - assets/images/crc.png
    - assets/images/cok.png
    - assets/images/cod.png
    - assets/images/cgo.png
    - assets/images/com.png
    - assets/images/col.png
    - assets/images/tpe.png
    - assets/images/chn.png
    - assets/images/chi.png
    - assets/images/cha.png
    - assets/images/cta.png
    - assets/images/cay.png
    - assets/images/can.png
    - assets/images/cmr.png
    - assets/images/cam.png
    - assets/images/cpv.png
    - assets/images/bdi.png
    - assets/images/bfa.png
    - assets/images/bul.png
    - assets/images/bru.png
    - assets/images/vgb.png
    - assets/images/bra.png
    - assets/images/bot.png
    - assets/images/bih.png
    - assets/images/bol.png
    - assets/images/bhu.png
    - assets/images/ber.png
    - assets/images/ben.png
    - assets/images/blz.png
    - assets/images/bel.png
    - assets/images/blr.png
    - assets/images/brb.png
    - assets/images/ban.png
    - assets/images/bhr.png
    - assets/images/bah.png
    - assets/images/aze.png
    - assets/images/aut.png
    - assets/images/aus.png
    - assets/images/aru.png
    - assets/images/arm.png
    - assets/images/arg.png
    - assets/images/atg.png
    - assets/images/aia.png
    - assets/images/ang.png
    - assets/images/asa.png
    - assets/images/alg.png
    - assets/images/alb.png
    - assets/images/and.png
    - assets/images/afg.png    
    - assets/audio/BouncingBall.mp3
    - assets/audio/whistle.mp3
    - assets/audio/goal_robot.mp3
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
